# Try to find OpenGLES2. Once done this will define:
#     OPENGLES2_FOUND
#     OPENGLES2_INCLUDE_DIR
#     OPENGLES2_LIBRARIES

FIND_PACKAGE(PkgConfig)

PKG_CHECK_MODULES(PC_OPENGLES2 glesv2)

FIND_PATH(OPENGLES2_INCLUDE_DIR GLES2/gl2.h
    HINTS ${PC_OPENGLES2_INCLUDE_DIRS} ${PC_OPENGLES2_INCLUDE_DIRS}
)

FIND_LIBRARY(OPENGLES2_LIBRARIES GLESv2
    HINTS ${PC_OPENGLES2_LIBRARY_DIRS} ${PC_OPENGLES2_LIBDIR}
)

MESSAGE("${PC_OPENGLES2_LIBRARY_DIRS}")
MESSAGE("${PC_OPENGLES2_LIBDIR}")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OpenGLES2 DEFAULT_MSG OPENGLES2_LIBRARIES)

MARK_AS_ADVANCED(OPENGLES2_INCLUDE_DIR OPENGLES2_LIBRARY)
