# Try to find OpenGLES2. Once done this will define:
#     OPENGLES2_FOUND
#     OPENGLES2_INCLUDE_DIRS
#     OPENGLES2_LIBRARIES
#     OPENGLES2_DEFINITIONS

FIND_PACKAGE(PkgConfig)

PKG_CHECK_MODULES(PC_OPENGLES2 glesv2)

IF (PC_OPENGLES2_FOUND)
    SET(OPENGLES2_INCLUDE_DIRS ${PC_OPENGLES2_INCLUDE_DIRS})
    SET(OPENGLES2_DEFINITIONS ${PC_OPENGLES2_CFLAGS_OTHER})
ELSE ()
    FIND_PATH(OPENGLES2_INCLUDE_DIRS NAMES GLES2/gl2.h)
ENDIF ()

FIND_LIBRARY(OPENGLES2_LIBRARIES GLESv2
    HINTS ${PC_OPENGLES2_LIBRARY_DIRS} ${PC_OPENGLES2_LIBDIR}
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OpenGLES2 DEFAULT_MSG OPENGLES2_LIBRARIES OPENGLES2_INCLUDE_DIRS)

MARK_AS_ADVANCED(OPENGLES2_INCLUDE_DIRS OPENGLES2_LIBRARY)
