SET(PROJECT_VERSION_MAJOR 0)
SET(PROJECT_VERSION_MINOR 1)
SET(PROJECT_VERSION_PATCH 0)
SET(PROJECT_VERSION ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH})

ADD_DEFINITIONS(-DBUILDING_NIX__=1)
ADD_DEFINITIONS(-DWTF_PLATFORM_NIX=1)
SET(WTF_PLATFORM_NIX 1)

FIND_PACKAGE(Cairo 1.10 REQUIRED)
FIND_PACKAGE(Fontconfig 2.8.0 REQUIRED)
FIND_PACKAGE(Sqlite REQUIRED)
FIND_PACKAGE(LibXml2 2.6 REQUIRED)
FIND_PACKAGE(LibXslt 1.1.7 REQUIRED)
FIND_PACKAGE(ICU REQUIRED)
FIND_PACKAGE(Threads REQUIRED)
FIND_PACKAGE(JPEG REQUIRED)
FIND_PACKAGE(PNG REQUIRED)
FIND_PACKAGE(ZLIB REQUIRED)
FIND_PACKAGE(OpenGL REQUIRED)

FIND_PACKAGE(GLIB 2.31.8 REQUIRED COMPONENTS gio gobject gthread)
FIND_PACKAGE(LibSoup 2.39.4.1 REQUIRED)
SET(ENABLE_GLIB_SUPPORT ON)

SET(WTF_USE_SOUP 1)
ADD_DEFINITIONS(-DWTF_USE_SOUP=1)

ADD_DEFINITIONS(-DENABLE_CONTEXT_MENUS=0)

SET(WTF_USE_PTHREADS 1)
ADD_DEFINITIONS(-DWTF_USE_PTHREADS=1)

SET(WTF_USE_ICU_UNICODE 1)
ADD_DEFINITIONS(-DWTF_USE_ICU_UNICODE=1)

SET(WTF_USE_CAIRO 1)
ADD_DEFINITIONS(-DWTF_USE_CAIRO=1)

SET(JSC_EXECUTABLE_NAME jsc)

SET(WTF_LIBRARY_NAME wtf_nix)
SET(JavaScriptCore_LIBRARY_NAME javascriptcore_nix)
SET(WebCore_LIBRARY_NAME webcore_nix)
SET(WebKit2_LIBRARY_NAME WebKitNix)

# Don't call WEBKIT_OPTION_BEGIN, the magic is made automagically for Nix
# and maybe for all ports when this patch goes up stream.
#
# Default feature list can be found at Tools/Scripts/webkitperl/FeatureDefaultsNix.txt
WEBKIT_OPTION_DEFINE(ENABLE_API_TESTS "Enable public API unit tests" ON)
WEBKIT_OPTION_DEFINE(WTF_USE_EGL "Use GLE instead of GLX" OFF)
WEBKIT_OPTION_END()

FIND_PACKAGE(Freetype REQUIRED)
FIND_PACKAGE(HarfBuzz REQUIRED)
SET(WTF_USE_FREETYPE 1)
SET(WTF_USE_HARFBUZZ_NG 1)
ADD_DEFINITIONS(-DWTF_USE_FREETYPE=1)
ADD_DEFINITIONS(-DWTF_USE_HARFBUZZ_NG=1)

IF (NOT ENABLE_SVG)
  SET(ENABLE_SVG_FONTS 0)
ENDIF ()

IF (ENABLE_BATTERY_STATUS)
    FIND_PACKAGE(DBus REQUIRED)
ENDIF ()

IF (ENABLE_VIDEO OR ENABLE_WEB_AUDIO)
    SET(GSTREAMER_COMPONENTS app interfaces pbutils)
    SET(WTF_USE_GSTREAMER 1)
    ADD_DEFINITIONS(-DWTF_USE_GSTREAMER=1)

    IF (ENABLE_VIDEO)
        LIST(APPEND GSTREAMER_COMPONENTS video)
    ENDIF()

    IF (ENABLE_WEB_AUDIO)
        LIST(APPEND GSTREAMER_COMPONENTS audio fft)
        ADD_DEFINITIONS(-DWTF_USE_WEBAUDIO_GSTREAMER=1)
    ENDIF ()

    FIND_PACKAGE(GStreamer REQUIRED COMPONENTS ${GSTREAMER_COMPONENTS})
ENDIF ()


IF (WTF_USE_EGL)
  FIND_PACKAGE(EGL REQUIRED)
ELSE ()
  SET(WTF_USE_GLX 1)
  ADD_DEFINITIONS(-DWTF_USE_GLX=1)
ENDIF ()

SET(CPACK_SOURCE_GENERATOR TBZ2)

SET(WTF_USE_ACCELERATED_COMPOSITING 1)
ADD_DEFINITIONS(-DWTF_USE_ACCELERATED_COMPOSITING=1)

SET(WTF_USE_COORDINATED_GRAPHICS 1)
ADD_DEFINITIONS(-DWTF_USE_COORDINATED_GRAPHICS=1)

SET(WTF_USE_TEXTURE_MAPPER 1)
ADD_DEFINITIONS(-DWTF_USE_TEXTURE_MAPPER=1)

SET(WTF_USE_TEXTURE_MAPPER_GL 1)
ADD_DEFINITIONS(-DWTF_USE_TEXTURE_MAPPER_GL=1)

SET(WTF_USE_3D_GRAPHICS 1)
ADD_DEFINITIONS(-DWTF_USE_3D_GRAPHICS=1)
